name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  inspector-scan:
    name: Amazon Inspector Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug GitHub OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::523835807940:role/GitHubActions-InspectorScan
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity
